#!/usr/bin/env sh
# verify.local.sh — repo-local static + hook tests, invoked automatically
# by scripts/run-verify.sh.
#
# Honors HARNESS_VERIFY_MODE to match the documented split in
# docs/quality/quality-gates.md:
#   - static: shellcheck, sh -n, jq validity, template sync
#   - test  : hook smoke tests (tests/test-check-mojibake.sh)
#   - all   : everything (default; what run-verify.sh sets)
#
# This file is NOT shipped to scaffolded projects; scaffolded projects
# should write their own verify.local.sh. See scripts/check-sync.sh
# ROOT_ONLY_EXCLUSIONS for the sync policy.

set -eu

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

mode="${HARNESS_VERIFY_MODE:-all}"
case "$mode" in
  static|test|all) ;;
  *)
    printf 'verify.local.sh: unknown HARNESS_VERIFY_MODE=%s (expected static|test|all)\n' "$mode" >&2
    exit 2
    ;;
esac

status=0

codex_config_has_inline_hooks() {
  config_file="$1"

  if command -v python3 >/dev/null 2>&1 && python3 -c 'import tomllib' >/dev/null 2>&1; then
    python3 -c '
import sys
import tomllib

with open(sys.argv[1], "rb") as fh:
    data = tomllib.load(fh)
sys.exit(0 if "hooks" in data else 1)
' "$config_file"
    return "$?"
  fi

  awk '
    /^[[:space:]]*\[/ {
      line = $0
      gsub(/[[:space:]]/, "", line)
      if (line ~ /^\[\[?hooks(\.|\]\]?)/) {
        found = 1
      }
    }
    END { exit found ? 0 : 1 }
  ' "$config_file"
}

check_codex_hook_single_source() {
  for base in "." "templates/base"; do
    config_file="${base}/.codex/config.toml"
    hooks_json="${base}/.codex/hooks.json"

    [ -f "$config_file" ] || continue

    if codex_config_has_inline_hooks "$config_file" && [ -f "$hooks_json" ]; then
      printf '%s\n' "Codex hook config: duplicate project-level hook representations detected"
      printf '%s\n' "  - ${config_file} contains inline hooks entries"
      printf '%s\n' "  - ${hooks_json} also exists"
      printf '%s\n' "Remove one representation; this repo uses .codex/config.toml as the source of truth."
      return 1
    fi
  done
}

test_codex_inline_hook_detector() {
  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

  with_hooks="$tmp_dir/with-hooks.toml"
  without_hooks="$tmp_dir/without-hooks.toml"

  cat > "$with_hooks" <<'EOF'
model = "gpt-5.5"

[[ hooks.PostToolUse ]]
command = ["./.claude/hooks/check_mojibake.sh"]

[ hooks.PostToolUse.match ]
tool = "Edit"
EOF

  cat > "$without_hooks" <<'EOF'
model = "gpt-5.5"

[features]
hooks = true
EOF

  codex_config_has_inline_hooks "$with_hooks"
  if codex_config_has_inline_hooks "$without_hooks"; then
    printf '%s\n' "Codex inline hook detector: false positive for config without hooks"
    return 1
  fi
}

check_codex_pr_provenance_policy() {
  for file in .codex/AGENTS.override.md templates/base/.codex/AGENTS.override.md; do
    [ -f "$file" ] || {
      printf '%s\n' "Codex PR provenance policy: missing ${file}"
      return 1
    }

    for needle in \
      "titles, PR bodies" \
      "chore(codex)" \
      "chore(claude)" \
      "chore(cursor)" \
      "Generated by Codex" \
      "Generated by Claude" \
      "Generated by Cursor" \
      "PR author or creator"
    do
      if ! grep -F "$needle" "$file" >/dev/null 2>&1; then
        printf '%s\n' "Codex PR provenance policy: ${file} is missing required wording: ${needle}"
        return 1
      fi
    done
  done
}

run() {
  label="$1"
  shift
  printf '==> %s\n' "$label"
  if "$@"; then
    printf '    OK\n'
  else
    printf '    FAIL\n'
    status=1
  fi
}

run_static_checks() {
  # 1. Shellcheck on hook and verification shell scripts (if available).
  if command -v shellcheck >/dev/null 2>&1; then
    # Build the argument list via positional parameters so shellcheck
    # does not flag unquoted expansion.
    set --
    for f in .claude/hooks/*.sh templates/base/.claude/hooks/*.sh scripts/branch-name.sh scripts/ensure-pr-ready.sh scripts/ensure-pr-title-prefix.sh scripts/ralph-worktree.sh scripts/verify.local.sh scripts/ralph-common.sh scripts/xreview-helpers.sh tests/test-*.sh; do
      [ -f "$f" ] || continue
      set -- "$@" "$f"
    done
    if [ "$#" -gt 0 ]; then
      # --severity=warning: info-level hints (SC1091 unfollowable source,
      # SC2015 A&&B||C, SC2016 single-quoted expansions, SC2317 unreachable
      # in trap handlers) are style advisories, not gate-worthy defects.
      run "shellcheck hook + verify scripts" shellcheck --severity=warning "$@"
    fi
  else
    printf '==> shellcheck not installed; skipping (install for stricter checks)\n'
  fi

  # 2. Syntax check every .sh in .claude/hooks/.
  for f in .claude/hooks/*.sh templates/base/.claude/hooks/*.sh; do
    [ -f "$f" ] || continue
    run "sh -n $f" sh -n "$f"
  done

  # 3. JSON validity for settings.json.
  if command -v jq >/dev/null 2>&1; then
    for f in .claude/settings.json templates/base/.claude/settings.json; do
      [ -f "$f" ] || continue
      run "jq -e . $f" jq -e . "$f"
    done
  else
    printf '==> jq not installed; skipping JSON validity check\n'
  fi

  # 4. Codex hook configuration: one project-layer representation only.
  run "Codex hook single-source guard" check_codex_hook_single_source
  run "Codex inline hook detector smoke test" test_codex_inline_hook_detector
  run "Codex PR provenance policy guard" check_codex_pr_provenance_policy

  # 5. Template sync.
  if [ -x scripts/check-sync.sh ]; then
    run "scripts/check-sync.sh" scripts/check-sync.sh
  fi

  # 6. Pipeline order sync.
  if [ -x scripts/check-pipeline-sync.sh ]; then
    run "scripts/check-pipeline-sync.sh" scripts/check-pipeline-sync.sh
  fi

  # 7. Skill drift between .claude/skills/ and .agents/skills/. The Codex
  # parity contract relies on these trees staying byte-identical (body) and
  # carrying matching trigger metadata (name/description/policy).
  if [ -x scripts/check-skill-sync.sh ]; then
    run "scripts/check-skill-sync.sh" scripts/check-skill-sync.sh
  fi
}

run_hook_tests() {
  # Run every tests/test-*.sh, not a hand-maintained list: enumeration drift
  # left 5 of 28 suites (ralph-config, ralph-signals, ralph-status,
  # xreview-gate-regression, xreview-prompt-render) silently unexecuted.
  for f in tests/test-*.sh; do
    [ -x "$f" ] || continue
    run "$f" "$f"
  done
}

case "$mode" in
  static) run_static_checks ;;
  test)   run_hook_tests ;;
  all)    run_static_checks; run_hook_tests ;;
esac

exit "$status"
