#!/usr/bin/env sh
# verify.local.sh — repo-local static + hook tests, invoked automatically
# by scripts/run-verify.sh.
#
# Honors HARNESS_VERIFY_MODE to match the documented split in
# docs/quality/quality-gates.md:
#   - static: shellcheck, sh -n, jq validity, template sync, tech-debt
#             plan references
#   - test  : every tests/test-*.sh (a file without the exec bit, in the
#             working tree or the git index, counts as a failure)
#   - all   : everything (default; what run-verify.sh sets)
#
# This file is NOT shipped to scaffolded projects; scaffolded projects
# should write their own verify.local.sh. See scripts/check-sync.sh
# ROOT_ONLY_EXCLUSIONS for the sync policy.

set -eu

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

mode="${HARNESS_VERIFY_MODE:-all}"
case "$mode" in
  static|test|all) ;;
  *)
    printf 'verify.local.sh: unknown HARNESS_VERIFY_MODE=%s (expected static|test|all)\n' "$mode" >&2
    exit 2
    ;;
esac

status=0

codex_config_has_inline_hooks() {
  config_file="$1"

  if command -v python3 >/dev/null 2>&1 && python3 -c 'import tomllib' >/dev/null 2>&1; then
    python3 -c '
import sys
import tomllib

with open(sys.argv[1], "rb") as fh:
    data = tomllib.load(fh)
sys.exit(0 if "hooks" in data else 1)
' "$config_file"
    return "$?"
  fi

  awk '
    /^[[:space:]]*\[/ {
      line = $0
      gsub(/[[:space:]]/, "", line)
      if (line ~ /^\[\[?hooks(\.|\]\]?)/) {
        found = 1
      }
    }
    END { exit found ? 0 : 1 }
  ' "$config_file"
}

check_codex_hook_single_source() {
  for base in "." "templates/base"; do
    config_file="${base}/.codex/config.toml"
    hooks_json="${base}/.codex/hooks.json"

    [ -f "$config_file" ] || continue

    if codex_config_has_inline_hooks "$config_file" && [ -f "$hooks_json" ]; then
      printf '%s\n' "Codex hook config: duplicate project-level hook representations detected"
      printf '%s\n' "  - ${config_file} contains inline hooks entries"
      printf '%s\n' "  - ${hooks_json} also exists"
      printf '%s\n' "Remove one representation; this repo uses .codex/hooks.json as the source of truth — delete the config.toml [hooks]/[[hooks.*]] entries."
      return 1
    fi
  done
}

test_codex_inline_hook_detector() {
  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

  with_hooks="$tmp_dir/with-hooks.toml"
  without_hooks="$tmp_dir/without-hooks.toml"

  cat > "$with_hooks" <<'EOF'
model = "gpt-5.5"

[[ hooks.PostToolUse ]]
command = ["./.claude/hooks/check_mojibake.sh"]

[ hooks.PostToolUse.match ]
tool = "Edit"
EOF

  cat > "$without_hooks" <<'EOF'
model = "gpt-5.5"

[features]
hooks = true
EOF

  codex_config_has_inline_hooks "$with_hooks"
  if codex_config_has_inline_hooks "$without_hooks"; then
    printf '%s\n' "Codex inline hook detector: false positive for config without hooks"
    return 1
  fi
}

check_codex_pr_provenance_policy() {
  for file in .codex/AGENTS.override.md templates/base/.codex/AGENTS.override.md; do
    [ -f "$file" ] || {
      printf '%s\n' "Codex PR provenance policy: missing ${file}"
      return 1
    }

    for needle in \
      "titles, PR bodies" \
      "chore(codex)" \
      "chore(claude)" \
      "chore(cursor)" \
      "Generated by Codex" \
      "Generated by Claude" \
      "Generated by Cursor" \
      "PR author or creator"
    do
      if ! grep -F "$needle" "$file" >/dev/null 2>&1; then
        printf '%s\n' "Codex PR provenance policy: ${file} is missing required wording: ${needle}"
        return 1
      fi
    done
  done
}

# check_tech_debt_plan_refs — every docs/plans/active/<x> and
# docs/plans/archive/<x> reference in docs/tech-debt/README.md exists at
# exactly that path (-e: file and directory plans both count). One trailing
# "." is dropped so a sentence-ending period is not part of the name.
# scripts/archive-plan.sh rewrites these references when it archives a plan,
# with the same name boundary (one trailing "." is not part of the name);
# this catches a plan moved by hand. Prints each missing reference. No README,
# nothing to check.
check_tech_debt_plan_refs() {
  readme="docs/tech-debt/README.md"
  [ -f "$readme" ] || return 0
  missing="$(grep -o -E 'docs/plans/(active|archive)/[A-Za-z0-9._-]+' "$readme" \
    | sed 's/\.$//' | sort -u \
    | while IFS= read -r ref; do
        [ -e "$ref" ] || printf '%s\n' "$ref"
      done)"
  if [ -n "$missing" ]; then
    printf '%s\n' "${readme} references plans that do not exist at that path:"
    printf '%s\n' "$missing" | sed 's/^/  - /'
    return 1
  fi
}

run() {
  label="$1"
  shift
  printf '==> %s\n' "$label"
  if "$@"; then
    printf '    OK\n'
  else
    printf '    FAIL\n'
    status=1
  fi
}

run_static_checks() {
  # 1. Shellcheck on hook and verification shell scripts (if available).
  if command -v shellcheck >/dev/null 2>&1; then
    # Build the argument list via positional parameters so shellcheck
    # does not flag unquoted expansion. scripts/*.sh is a glob, not a
    # hand-maintained list: the list had drifted to cover 9 of 36 scripts
    # (scripts/insights-append.sh among the ones silently left out).
    set --
    for f in .claude/hooks/*.sh templates/base/.claude/hooks/*.sh scripts/*.sh tests/test-*.sh; do
      [ -f "$f" ] || continue
      set -- "$@" "$f"
    done
    if [ "$#" -gt 0 ]; then
      # --severity=warning: info-level hints (SC1091 unfollowable source,
      # SC2015 A&&B||C, SC2016 single-quoted expansions, SC2317 unreachable
      # in trap handlers) are style advisories, not gate-worthy defects.
      run "shellcheck hook + verify scripts" shellcheck --severity=warning "$@"
    fi
  else
    printf '==> shellcheck not installed; skipping (install for stricter checks)\n'
  fi

  # 2. Syntax check every .sh in .claude/hooks/.
  for f in .claude/hooks/*.sh templates/base/.claude/hooks/*.sh; do
    [ -f "$f" ] || continue
    run "sh -n $f" sh -n "$f"
  done

  # 3. JSON validity for settings.json.
  if command -v jq >/dev/null 2>&1; then
    for f in .claude/settings.json templates/base/.claude/settings.json; do
      [ -f "$f" ] || continue
      run "jq -e . $f" jq -e . "$f"
    done
  else
    printf '==> jq not installed; skipping JSON validity check\n'
  fi

  # 4. Codex hook configuration: one project-layer representation only.
  run "Codex hook single-source guard" check_codex_hook_single_source
  run "Codex inline hook detector smoke test" test_codex_inline_hook_detector
  run "Codex PR provenance policy guard" check_codex_pr_provenance_policy

  # 5. Template sync.
  if [ -x scripts/check-sync.sh ]; then
    run "scripts/check-sync.sh" scripts/check-sync.sh
  fi

  # 6. Pipeline order sync.
  if [ -x scripts/check-pipeline-sync.sh ]; then
    run "scripts/check-pipeline-sync.sh" scripts/check-pipeline-sync.sh
  fi

  # 7. Skill drift between .claude/skills/ and .agents/skills/. The Codex
  # parity contract relies on these trees staying byte-identical (body) and
  # carrying matching trigger metadata (name/description/policy).
  if [ -x scripts/check-skill-sync.sh ]; then
    run "scripts/check-skill-sync.sh" scripts/check-skill-sync.sh
  fi

  # 8. Template purity: templates/ (the go:embed source tree) must carry no
  # meta-repo-specific references (org handle, maintainer identifiers,
  # meta-repo-only tooling/CI/plan citations). FR-10.
  if [ -x scripts/check-template-purity.sh ]; then
    run "scripts/check-template-purity.sh" scripts/check-template-purity.sh
  fi

  # 9. Plan references in docs/tech-debt/README.md point at real plans.
  run "tech-debt README plan references" check_tech_debt_plan_refs
}

# hook_test_mode_problem FILE — print why FILE would not run as a test (no
# exec bit in the working tree, or a git index mode of 100644), or nothing.
# The index mode matters on its own: a local `chmod +x` leaves the index at
# 100644 until `git update-index --chmod=+x`, and CI checks out the index
# mode, so the test would not run there. The index is read only inside a
# git work tree; an untracked file has no index mode and relies on the
# working-tree bit.
hook_test_mode_problem() {
  test_file="$1"
  problem=""
  if [ ! -x "$test_file" ]; then
    problem="not executable in the working tree"
  fi
  if [ "$in_git_work_tree" = "true" ]; then
    index_mode="$(git ls-files -s -- "$test_file" | awk 'NR == 1 { print $1 }')"
    if [ "$index_mode" = "100644" ]; then
      problem="${problem:+${problem}; }git index mode is 100644"
    fi
  fi
  printf '%s' "$problem"
}

run_hook_tests() {
  # Run every tests/test-*.sh, not a hand-maintained list: enumeration drift
  # left 5 of 28 suites (ralph-config, ralph-signals, ralph-status,
  # xreview-gate-regression, xreview-prompt-render) silently unexecuted.
  # A test without the exec bit used to be skipped silently as well; it is
  # now a FAIL that names the file and the fix.
  in_git_work_tree="$(git rev-parse --is-inside-work-tree 2>/dev/null || true)"
  for f in tests/test-*.sh; do
    [ -f "$f" ] || continue
    mode_problem="$(hook_test_mode_problem "$f")"
    if [ -n "$mode_problem" ]; then
      printf '==> %s\n' "$f"
      printf '    FAIL: %s (%s)\n' "$mode_problem" "$f"
      printf '    fix: chmod +x %s\n' "$f"
      # The git half of the fix depends on whether git tracks the file yet:
      # update-index fails on an untracked path, which needs add --chmod.
      if [ "$in_git_work_tree" = "true" ]; then
        if git ls-files --error-unmatch -- "$f" >/dev/null 2>&1; then
          printf '         git update-index --chmod=+x %s\n' "$f"
        else
          printf '         git add --chmod=+x %s\n' "$f"
        fi
      fi
      status=1
      continue
    fi
    run "$f" "$f"
  done
}

case "$mode" in
  static) run_static_checks ;;
  test)   run_hook_tests ;;
  all)    run_static_checks; run_hook_tests ;;
esac

exit "$status"
