name: check-template

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check scaffold structure
        run: ./scripts/check-template.sh
      - name: Check template sync
        run: ./scripts/check-sync.sh
